sonar.projectKey=shangjung1012_Wafer-Fabrication-Scheduling
sonar.organization=shangjung1012

sonar.sources=.github,app,components,infra,lib,modules,prisma,scripts
sonar.tests=__tests__
sonar.exclusions=.next/**,coverage/**,node_modules/**,reports/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=.github/**,app/**/page.tsx,app/api/**/route.ts,infra/db/daily-execution-repository.ts,lib/redis.ts,modules/schedule/manual-edit-service.ts,modules/schedule/strategy.ts,prisma/**,scripts/**

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=Wafer-Fabrication-Scheduling
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
