sonar.projectKey=shangjung1012_Wafer-Fabrication-Scheduling
sonar.organization=shangjung1012


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=Wafer-Fabrication-Scheduling
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8